services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 15800:15672
#    expose:
#      - 5672
    networks: 
      - main-network
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      - ./secrets/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./secrets/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  job-collector-go:
    image: job-collector-go
    networks:
      - main-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    secrets:
      - hh_api_token
      - rabbitmq_user
      - rabbitmq_pass

networks:
  main-network:

secrets:
  rabbitmq_user:
    file: ./secrets/rabbitmq_user.txt
  rabbitmq_pass:
    file: ./secrets/rabbitmq_password.txt
  hh_api_token:
    file: ./secrets/hh_api_token.txt